---
version: 2.1
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: ${AWS_REGION}
          
  createFile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Create inventory file
          command: touch inventory.txt
      - run:
          name: Add group [all] to file
          command: echo [add] > inventory.txt

  addAddress:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Include address into inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> inventory.txt
      - run: echo inventory.txt
      - save_cache:
          key: inventory
          paths:
            - inventory.txt

workflows:
  myWorkflow:
    jobs:
      - createFile
      - addAddress:
          requires:
            - createFile

          