---
version: 2.1
jobs:
  createFile:
    docker:
      image: img/base:2021.04
    steps:
      - checkout
      - run:
          name: Create inventory file
          command: touch inventory.txt
      - run:
          name: Add group [all] to file
          command: echo [add] > inventory.txt

  addFddress:
    docker:
      image: amazon/aws-cli
    steps:
      - run:
          name: Include address into inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> inventory.txt
      - run: echo inventory.txt
      - save_cache:
          key: inventory
          paths:
            - inventory.txt

workflows:
  myWorkflow:
    jobs:
      - createFile
      - addAddress:
          requires:
            - createFile

          